name: Pull Request
on:
  pull_request:
jobs:
  build_and_test_windows:
    runs-on: windows-latest
    steps:
      - name: Get the sources
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.203

      - name: Clean
        run: dotnet clean --configuration Release && dotnet nuget locals all --clear

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet publish -o publish

      - name: Check Executable
        run: .\publish\etvctl.exe
  build_and_test_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Get the sources
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.203

      - name: Clean
        run: dotnet clean --configuration Release && dotnet nuget locals all --clear

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet publish -o publish

      - name: Check Executable
        run: ./publish/etvctl
  build_and_test_mac:
    runs-on: macos-13
    steps:
      - name: Get the sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.203

      - name: Clean
        run: dotnet clean --configuration Release && dotnet nuget locals all --clear

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet publish -o publish

      - name: Check Executable
        run: ./publish/etvctl
